### ISSUE TITLE
Prebuilt windows binaries electron 3.x aka ABI 64 dont seem to work

### ISSUE THREAD

**Issue by the-j0k3r** [oznu/node-pty-prebuilt-multiarch#1]
## Environment details

- OS: Windows 10 PRO/Enterprise 64 bit
- OS version: pro 1809/ enterprise 1903
- node-pty version: 0.8.1

## Issue description

Using [platformio-ide-terminal@2.9.3](https://github.com/platformio/platformio-atom-ide-terminal) which switched from node-pty-prebuilt 0.7.6 being compatible with Atom/ up to 1.38.2 electron version 2.0.0 and fully working with platformio-ide-terminal@2.9.1, now with Atom 1.39.1 and node-pty-prebuilt-multiarch 0.8.1 the terminal has only a blinking cursor.

Using rebuilt binaries with python 2.7.16 works, but the binaries here for at least Windows dont.

Rebuilt working binaries
[Release.zip](https://github.com/oznu/node-pty-prebuilt-multiarch/files/3460598/Release.zip)

Prebuilt non working  binaries.
[Release-prebuilt.zip](https://github.com/oznu/node-pty-prebuilt-multiarch/files/3460607/Release-prebuilt.zip)

I suspect its the python version used to compile them in this repo, but it could be something else that eludes me at this time.

**Comment by oznu** [comment]
I don't build for Electron 3.0 on Windows 10.

https://github.com/oznu/node-pty-prebuilt-multiarch/blob/prebuilt-multiarch/.travis.yml#L63-L67

I'm sure there was a reason why, but I'll try updating it to see.

**Comment by the-j0k3r** [comment]
Appreciated

**Comment by oznu** [comment]
It seemed to work in Travis.

To install use the `next` tag:

```
npm install node-pty-prebuilt-multiarch@next
```

---

For some reason the Windows builds are being marked as failed even though they pass and exit with code 0. I'm going to ignore that issue for now as it's not actually breaking anything and probably just a Travis thing.

![image](https://user-images.githubusercontent.com/3979615/62371111-58f99c80-b577-11e9-954b-9d0f35966289.png)

**Comment by the-j0k3r** [comment]
Well but how to solve this as a dependency for platformio-ide-terminal? It needs prebuilt binaries there.

I chose this project because node-pty-prebuilt has pretty much been silent for months and its incompatible with electron 3.x and higher in some platforms, which Atom 1.39.1 is sporting

**Comment by oznu** [comment]
Replacing `^0.8.1` with `0.9.0-beta21.1` should do it.

I can't build 0.8.1 as it's got some issues making it incompatible with the latest Node.js version - hence why I'm building the pre-release betas.

**Comment by the-j0k3r** [comment]
OK will do that, though I noticed that there are no electron 3.x prebuilds for macOS https://github.com/oznu/node-pty-prebuilt-multiarch/blob/6e960ae0c55f95c35af41f8fbdec8dcd75d0dea6/.travis.yml#L61 :sob: 

Im not ure about Linux side, does that support electron 3.x? If not would you also?

**Comment by the-j0k3r** [comment]
Ah I see Linux builds all... its just that pesky macOS failing for some reason. =(

**Comment by the-j0k3r** [comment]
THe Windows builds Travis fails because of failed to upload cache, so it can be ignored or if a fix is possible apply it.

Here is relevant part of log.
```log
prebuild info build Prebuild written to prebuilds\node-pty-prebuilt-multiarch-v0.9.0-beta21.1-electron-v70-win32-ia32.tar.gz
1823
gzip: warning: GZIP environment variable is deprecated; use an alias or script
1824
uploading cache-windows-1803-containers-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--node-lts/*.tgz
1825
failed to upload cache
```

**Comment by the-j0k3r** [comment]
Seems working now both with this and 0.9.0-beta21.legacy both Windows macoOS Linux

Closing, and thank you again so much.
