### ISSUE TITLE
Any chance for adding SmartOS support?

### ISSUE THREAD

**Issue by liv3010m** [oznu/node-pty-prebuilt-multiarch#10]
## Environment details

- OS: SmartOS
- OS version: joyent_20200212T230824Z
- node-pty version: 0.9.0

## Issue description

Came here because I wanted to install homebridge-config-ui-x.
The problem was when NPM wanted to install node-pty-prebuilt-multiarch dependency, it couldn't complete the process giving this messages:

`585 info lifecycle tar-fs@2.0.0~install: tar-fs@2.0.0`
`1586 silly install simple-get@3.1.0`
`1587 info lifecycle simple-get@3.1.0~install: simple-get@3.1.0`
`1588 silly install nan@2.14.0`
`1589 info lifecycle nan@2.14.0~install: nan@2.14.0`
`1590 silly install prebuild-install@5.3.3`
`1591 info lifecycle prebuild-install@5.3.3~install: prebuild-install@5.3.3`
`1592 silly install node-pty-prebuilt-multiarch@0.9.0`
`1593 info lifecycle node-pty-prebuilt-multiarch@0.9.0~install: node-pty-prebuilt-multiarch@0.9.0`
`1594 verbose lifecycle node-pty-prebuilt-multiarch@0.9.0~install: unsafe-perm in lifecycle true`
`1595 verbose lifecycle node-pty-prebuilt-multiarch@0.9.0~install: PATH: /opt/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/local/lib/node_modules/node-pty-prebuilt-multiarch/node_modules/.bin:/opt/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/opt/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin`
`1596 verbose lifecycle node-pty-prebuilt-multiarch@0.9.0~install: CWD: /opt/local/lib/node_modules/node-pty-prebuilt-multiarch`
`1597 silly lifecycle node-pty-prebuilt-multiarch@0.9.0~install: Args: [ '-c', 'prebuild-install || node scripts/install.js' ]`
`1598 silly lifecycle node-pty-prebuilt-multiarch@0.9.0~install: Returned: code: 1  signal: null`
`1599 info lifecycle node-pty-prebuilt-multiarch@0.9.0~install: Failed to exec install script`
`1600 timing action:install Completed in 1563ms`
`1601 verbose unlock done using /root/.npm/_locks/staging-7d8aee99cce02c78.lock for /opt/local/lib/node_modules/.staging`
`1602 timing stage:rollbackFailedOptional Completed in 126ms`
`1603 timing stage:runTopLevelLifecycles Completed in 3909ms`
`1604 verbose stack Error: node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js``
`1604 verbose stack Exit status 1`
`1604 verbose stack     at EventEmitter.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)`
`1604 verbose stack     at EventEmitter.emit (events.js:311:20)`
`1604 verbose stack     at ChildProcess.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)`
1604 verbose stack     at ChildProcess.emit (events.js:311:20)`
1604 verbose stack     at maybeClose (internal/child_process.js:1021:16)`
`1604 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)`
`1605 verbose pkgid node-pty-prebuilt-multiarch@0.9.0`
`1606 verbose cwd /root`
`1607 verbose SunOS 5.11`
`1608 verbose argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "-g" "--unsafe-perm" "node-pty-prebuilt-multiarch"`
`1609 verbose node v12.16.1`
`1610 verbose npm  v6.13.7`
`1611 error code ELIFECYCLE`
`1612 error errno 1`
`1613 error node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js``
`1613 error Exit status 1`
`1614 error Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.`
`1614 error This is probably not a problem with npm. There is likely additional logging output above.`
`1615 verbose exit [ 1, true ]`

**Comment by oznu** [comment]
The package should attempt to compile locally if a prebuilt binary is not available.

Make sure you have the equivalents of `python python3 make gcc g++` installed.

**Comment by liv3010m** [comment]
Hi oznu,

Thank you so much. After installing gcc7(w. g++) and gmake (python3.7x was already installed) it worked:

`# npm install -g --unsafe-perm node-pty-prebuilt-multiarch`
``
`> node-pty-prebuilt-multiarch@0.9.0 install /opt/local/lib/node_modules/node-pty-prebuilt-multiarch`
`> prebuild-install || node scripts/install.js`
``
`prebuild-install WARN install No prebuilt binaries found (target=12.16.1 runtime=node arch=x64 libc= platform=sunos)`
`make: Entering directory '/opt/local/lib/node_modules/node-pty-prebuilt-multiarch/build'`
`  CXX(target) Release/obj.target/pty/src/unix/pty.o`
`  SOLINK_MODULE(target) Release/obj.target/pty.node`
`  COPY Release/pty.node`
`make: Leaving directory '/opt/local/lib/node_modules/node-pty-prebuilt-multiarch/build'`
``
`> node-pty-prebuilt-multiarch@0.9.0 postinstall /opt/local/lib/node_modules/node-pty-prebuilt-multiarch`
`> node scripts/post-install.js`
``
`+ node-pty-prebuilt-multiarch@0.9.0`
`added 59 packages from 41 contributors in 8.95s`

Verification:
`# npm list -g | grep prebuilt`
`+-- node-pty-prebuilt-multiarch@0.9.0`

Now homebridge-config-ui-x installation succeded  :)
`# npm list -g | grep home`
`+-- homebridge@0.4.52`
`+-- homebridge-config-ui-x@4.7.0-test.9`

Thanks again!
