### ISSUE TITLE
Need NODE_MODULE_VERSION 76 support

### ISSUE THREAD

**Issue by slimjimsoftware** [oznu/node-pty-prebuilt-multiarch#11]
## Environment details

- OS: all

## Issue description

Electron 8+ uses NODE_MODULE_VERSION 76, the last build for this module is 75 so this does not work with Electron 8. Please add NODE_MODULE_VERSION 76 support.

**Comment by oznu** [comment]
Done. There is no need to update the npm package.

**Comment by oznu** [comment]
https://github.com/oznu/node-pty-prebuilt-multiarch/releases/tag/v0.9.0

![image](https://user-images.githubusercontent.com/3979615/76134771-089a6e00-6075-11ea-83c9-517780af46fd.png)
