### ISSUE TITLE
No binaries for Electron 9

### ISSUE THREAD

**Issue by slimjimsoftware** [oznu/node-pty-prebuilt-multiarch#12]
## Environment details

- OS: all
- OS version: all
- node-pty version: 0.9.0

## Issue description
Not possible to use with Electron -  "prebuild-install WARN install No prebuilt binaries found (target=9.1.0 runtime=electron arch=x64 libc= platform=win32)"

**Comment by oznu** [comment]
Binaries for Electron 5 -> 11 (ABI 80) will be available in the 0.10.0 release.
